### ISSUE TITLE
Database connection error handling should be improved

### ISSUE THREAD

**Issue by henno** [maksimgru/dmp#1]
I glanced over DB_NAME and didn't change it which lead to this error:

( ! ) Fatal error: Uncaught Error: Call to a member function prepare() on null in /Users/henno/Sites/dmp/app/Models/UserModel.php on line 247

It took a while until I figured out the problem. How I found out the cause: I debugged and found that $this->db was null and found that it was supposed to get its value through Database::connect() which instantiated the db but it was done within try block and the catch block did not do anything particular with the error (just set it to $this->errors which was never used). I moved the $this->database = new \PDO line out of the try block and then saw the real error (Unknown database 'my_db_name').

Do you have plans to expand this catch block?

**Comment by maksimgru** [comment]
Sorry, but this is simple demo source. 
I understand that, ideally, there are a lot of improvements needed.
